### PR TITLE
CMIM python wrapper

### PR DESCRIPTION
**Pull request by EvgeniDubov**
- wrapped CMIM in python
- supports Linux and Windows
- added python unittest to test CMIM python wrapper and demonstrate usage
- tested on Python 3.5 Windows and Ubuntu
- included pre built CMIM libraries for Linux (.so) and Windows (.dll) in python/lib/
- I'm working at Intel and my group asked to add a contribution note in the code, need your advise on how to do that (added one line in py files)

### CODE REVIEW

**Comment by Craigacp** [comment]
Hi Evgeni,

I'd prefer not to have binaries checked into the git repository as they will age out as the source changes, so please remove them. WRT the contribution note you could add an Intel copyright statement to the top of the python file, and add an AUTHORS file with the names of the people who worked on this bit. I'll put my name in the AUTHORS file once you've added it and then we've got complete attribution.

Could you merge this into develop rather than master? At some point before it lands in master I'll need to build this out to cover all the algorithms, I don't want to have preferential support for one algorithm in one wrapper. Please ask your group what should happen to the contribution note if I have to refactor this to expose all the algorithms (I expect to do it like the Java and Matlab wrappers where there is a single file that has a method for each of the available algorithms).

Thanks,

Adam

**Comment by Craigacp** [comment]
Hi Evgeni,

It looks like you've spent some more time on this recently, is it ready for merging now or are there things you still need to do?

Thanks,

Adam

**Comment by EvgeniDubov** [comment]
Hi Adam, 
I've added a python wrapper for weightedCMIM (adding to the existing wrapper for CMIM)
suggesting to merge the two wrappers and add additional as we go 
Thanks

**Comment by Craigacp** [comment]
Looks good, I've merged it in. Is it worth making a setup.py which can compile the C libraries and install everything in a single pass?

**Comment by EvgeniDubov** [comment]
Thanks for merging @Craigacp 

Sounds great, I guess not only Python but also Java and MATLAB users would enjoy a single pass build script.
Regarding the pass itself, MIToolbox complicates things a bit as it is in a separate repo. The comprehensive build script will be located in FEAST repo while knowing the exact MIToolbox source structure. Another thing is that the user will need two separate clones and direct the build script to MIToolbox source location. 

For python I can suggest building a wheel file and uploading it to [PyPi](https://pypi.org/)
You'll reach a huge audience that way, as your implementation is much faster than the existing python solutions.

Please let me know if you need help with it

**Comment by Craigacp** [comment]
Yeah, I agree the build process is not ideal. I’ve been thinking about making MIToolbox appear as a git submodule in FEAST, which would make it easier to control the version and ensure everything is in a predefined place at compile time, making all the builds simpler. It’s on my list of things to investigate when I get some free time.

I agree that putting it on PyPi would be a good idea, after we’ve built out the remaining algorithms Python interfaces (and figured out the build).

**Comment by Craigacp** [comment]
I've rearranged the devel branch a little to use a submodule for MIToolbox and to make the python wrapper look a little more like a python package. The python parts aren't done yet, I need to test out the setup.py I wrote a bit more, but that's the direction it's going.

**Pull request merged**
