### PR TITLE
building FEAST dll to use the implementation on windows (linking MIToolbox statically)

### PR DESCRIPTION
**Pull request by EvgeniDubov**
- added windows dll build rules to makefile, including static link to pre built MIToolbox.a
- added windows build instructions to readme

### CODE REVIEW

**Comment by Craigacp** [comment]
This causes build errors if you haven't built MIToolbox statically. Could you fix the makefile so the Windows dll uses a different path so the Linux/macOS path doesn't require static linking?

Thanks,

Adam

**Comment by EvgeniDubov** [comment]
Hi Adam,
looks like Feast is built successfully even when MIToolbox is not present because it is linked to it dynamically, so I assume you want me to do the same for Windows, meaning build MIToolbox dll and then make Feast link to it dynamically.

No problem, I'll add the required changes to MIToolbox and Feast.

Thanks,
Evgeni

**Comment by Craigacp** [comment]
You can do dynamic linking for a FEAST dll, I'm not too bothered either way, but the current pull request statically links each .o file to MIToolbox.a rather than linking it when you create the dll. This causes issues with the unix builds, as they use dynamic linking.

**Comment by EvgeniDubov** [comment]
Updated the build instructions and tested on Windows and Ubuntu

**Comment by Craigacp** [comment]
Looks good. Thanks.

**Pull request merged**
